let myArray = ['Cokelat', 42.5, 22, true, 'Programming'];

console.log(myArray);
console.log(myArray[1]);
console.log(myArray.length);
myArray.push('Javascript');
console.log(myArray);
myArray.pop();
console.log(myArray);
myArray.shift();
console.log(myArray);
myArray.unshift('Apple');
console.log(myArray);
delete myArray[1];
console.log(myArray);
myArray.splice(2, 1);
console.log(myArray);
myArray.splice(1, 0, 'Iron man');
console.log(myArray);
myArray.splice(2, 1);
console.log(myArray);